print("{0}, {1}, {2}".format("a", "b", "c"))
print("{}, {}, {}".format("a", "b", "c"))
print("{2}, {1}, {0}".format("a", "b", "c"))
print("{0}{1}{0}".format("abra", "cad"))
print("{:*<20}".format("Vlevo"))
print("{:*>20}".format("Vpravo"))
print("{:*^20}".format("Uprostred"))
print("{:*^20}".format("Uprostred"))
print("int: {0:d}, hex: {0:x}, oct: {0:o}, bin: {0:b}".format(42))
print("{:,}".format(123456789))
